name = "codeDownload"
uuid = "bd4c7e8f-1484-4e9b-8bc9-df9ecf74baa6"
authors = ["Martin Alfaro <50346244+alfaromartino@users.noreply.github.com>"]
version = "0.1.0"

[deps]
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
